""" GPIO PIN GUI_ui.py --

 UI generated by GUI Builder Build 146 on 2016-01-07 19:33:53 from:
    Z:/Users/Carlos/Downloads/GPIO PIN GUI.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class GPIO_PIN_GUI(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self.pin = Tkinter.Label(root,
            text = "Pines",
        )
        self._button_4 = Tkinter.Button(root,
            text = 2 ,
        )
        self._button_6 = Tkinter.Button(root,
            text = 3 ,
        )
        self._label_2 = Tkinter.Label(root,
            text = "GND",
        )
        self._label_3 = Tkinter.Label(root,
            text = "3v3",
        )
        self._label_4 = Tkinter.Label(root,
            text = "5v",
        )
        self._label_5 = Tkinter.Label(root,
            text = "5v",
        )
        self._button_8 = Tkinter.Button(root,
            text = 4,
        )
        self._label_6 = Tkinter.Label(root,
            text = "GND",
        )
        self._button_9 = Tkinter.Button(root,
            text = 14 ,
        )
        self._button_10 = Tkinter.Button(root,
            text = 15 ,
        )
        self._button_11 = Tkinter.Button(root,
            text = 17,
        )
        self._button_12 = Tkinter.Button(root,
            text = 27,
        )
        self._button_13 = Tkinter.Button(root,
            text = 22,
        )
        self._button_14 = Tkinter.Button(root,
            text = 18,
        )
        self._button_15 = Tkinter.Button(root,
            text = 23,
        )
        self._label_7 = Tkinter.Label(root,
            text = "GND",
        )
        self._label_8 = Tkinter.Label(root,
            text = "3v3",
        )
        self._button_16 = Tkinter.Button(root,
            text = 24,
        )
        self._button_18 = Tkinter.Button(root,
            text = 10,
        )
        self._label_9 = Tkinter.Label(root,
            text = "GND",
        )
        self._button_19 = Tkinter.Button(root,
            text = 9,
        )
        self._button_20 = Tkinter.Button(root,
            text = 25,
        )
        self._button_21 = Tkinter.Button(root,
            text = 11,
        )
        self._button_22 = Tkinter.Button(root,
            text = 8,
        )
        self._button_23 = Tkinter.Button(root,
            text = 7,
        )
        self._label_10 = Tkinter.Label(root,
            text = "GND",
        )

        # widget commands

        self._button_4.configure(
            command = lambda: OnButtonClick(2)
        )
        self._button_6.configure(
            command = lambda: OnButtonClick(3)
        )
        self._button_8.configure(
            command = lambda: OnButtonClick(4)
        )
        self._button_9.configure(
            command = lambda: OnButtonClick(14)
        )
        self._button_10.configure(
            command = lambda: OnButtonClick(15)
        )
        self._button_11.configure(
            command = lambda: OnButtonClick(17)
        )
        self._button_12.configure(
            command = lambda: OnButtonClick(27)
        )
        self._button_13.configure(
            command = lambda: OnButtonClick(22)
        )
        self._button_14.configure(
            command = lambda: OnButtonClick(18)
        )
        self._button_15.configure(
            command = lambda: OnButtonClick(23)
        )
        self._button_16.configure(
            command = lambda: OnButtonClick(24)
        )
        self._button_18.configure(
            command = lambda: OnButtonClick(10)
        )
        self._button_19.configure(
            command = lambda: OnButtonClick(9)
        )
        self._button_20.configure(
            command = lambda: OnButtonClick(25)
        )
        self._button_21.configure(
            command = lambda: OnButtonClick(11)
        )
        self._button_22.configure(
            command = lambda: OnButtonClick(8)
        )
        self._button_23.configure(
            command = lambda: OnButtonClick(7)
        )


        # Geometry Management
        self.pin.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_4.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_6.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_2.grid(
            in_    = root,
            column = 2,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_3.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_4.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_5.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_8.grid(
            in_    = root,
            column = 1,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_6.grid(
            in_    = root,
            column = 1,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_9.grid(
            in_    = root,
            column = 2,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_10.grid(
            in_    = root,
            column = 2,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_11.grid(
            in_    = root,
            column = 1,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_12.grid(
            in_    = root,
            column = 1,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_13.grid(
            in_    = root,
            column = 1,
            row    = 9,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_14.grid(
            in_    = root,
            column = 2,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_15.grid(
            in_    = root,
            column = 2,
            row    = 9,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_7.grid(
            in_    = root,
            column = 2,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_8.grid(
            in_    = root,
            column = 1,
            row    = 10,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_16.grid(
            in_    = root,
            column = 2,
            row    = 10,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_18.grid(
            in_    = root,
            column = 1,
            row    = 11,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_9.grid(
            in_    = root,
            column = 2,
            row    = 11,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_19.grid(
            in_    = root,
            column = 1,
            row    = 12,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_20.grid(
            in_    = root,
            column = 2,
            row    = 12,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_21.grid(
            in_    = root,
            column = 1,
            row    = 13,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_22.grid(
            in_    = root,
            column = 2,
            row    = 13,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_23.grid(
            in_    = root,
            column = 2,
            row    = 14,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_10.grid(
            in_    = root,
            column = 1,
            row    = 14,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 46, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(5, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(6, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(7, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(8, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(9, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(10, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(11, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(12, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(13, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(14, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 100, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 100, pad = 0)
